name: Plan step

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-paths:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    outputs:
      services-list: ${{ steps.get-service.outputs.json-paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0 # 2022-03-01
        with:
          fetch-depth: 0

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v32
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          dir_names: "true"

      - name: Get service
        id: get-service
        run: |
          echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
          declare -A changes=()
          for value in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
            changes[$value]=1
          done
          new_array=()
          for item in "${services[@]}"; do
            new_array+=("$item")
          done
          echo "${new_array[@]}"
          json="$(jq --compact-output --null-input '$ARGS.positional' --args -- "${new_array[@]}")"
          echo $json
          echo "::set-output name=json-paths::$json"
