name: Plan step

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-paths:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    outputs:
      services-list: ${{ steps.get-service.outputs.json-paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0 # 2022-03-01
        with:
          fetch-depth: 0

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v32
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          dir_names: "true"

      - name: Get service
        id: get-service
        run: |
          echo ${{ steps.changed-files-dir-names.outputs.all_changed_files }}
          new_array=()
          for value in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
            new_array+=("$value")
          done
          echo "${new_array[@]}"
          json="$(jq --compact-output --null-input '$ARGS.positional' --args -- "${new_array[@]}")"
          echo $json
          echo "::set-output name=json-paths::$json"

  plan:
    if: ${{ needs.extract-paths.outputs.services-list != '[]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    needs: extract-paths
    strategy:
      matrix:
        new_path: ${{fromJson(needs.extract-paths.outputs.services-list)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0 # 2022-03-01

      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v6.0.0 # 2022-02-11
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha

      - name: Echo the PR sha
        run: |
          echo ${{ steps.sha.outputs.result }}
